//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelProsj4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Phone_nr { get; set; }
        public int Room_id { get; set; }
        public System.DateTime Check_in { get; set; }
        public System.DateTime Check_out { get; set; }
        public Nullable<int> price { get; set; }
        public int R_id { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
