//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelProsj4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Task_id { get; set; }
        public int Room_id { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
